name: fix_in_art
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.1.3


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Mont
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  assets:
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/linkedin.png
    - assets/images/about_fix_in_art.png
  uses-material-design: true

